# Generated by Django 6.0.2 on 2026-03-02 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_scheduleexception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleexception',
            unique_together={('doctor', 'date')},
        ),
    ]
